//! Whisper's supported transcription languages: (code, Czech display name).
//! Used to build the "Jazyk přepisu" submenu.

pub const LANGUAGES: &[(&str, &str)] = &[
    ("en", "Angličtina"),
    ("zh", "Čínština"),
    ("de", "Němčina"),
    ("es", "Španělština"),
    ("ru", "Ruština"),
    ("ko", "Korejština"),
    ("fr", "Francouzština"),
    ("ja", "Japonština"),
    ("pt", "Portugalština"),
    ("tr", "Turečtina"),
    ("pl", "Polština"),
    ("ca", "Katalánština"),
    ("nl", "Nizozemština"),
    ("ar", "Arabština"),
    ("sv", "Švédština"),
    ("it", "Italština"),
    ("id", "Indonéština"),
    ("hi", "Hindština"),
    ("fi", "Finština"),
    ("vi", "Vietnamština"),
    ("he", "Hebrejština"),
    ("uk", "Ukrajinština"),
    ("el", "Řečtina"),
    ("ms", "Malajština"),
    ("cs", "Čeština"),
    ("ro", "Rumunština"),
    ("da", "Dánština"),
    ("hu", "Maďarština"),
    ("ta", "Tamilština"),
    ("no", "Norština"),
    ("th", "Thajština"),
    ("ur", "Urdština"),
    ("hr", "Chorvatština"),
    ("bg", "Bulharština"),
    ("lt", "Litevština"),
    ("la", "Latina"),
    ("mi", "Maorština"),
    ("ml", "Malajálamština"),
    ("cy", "Velština"),
    ("sk", "Slovenština"),
    ("te", "Telugština"),
    ("fa", "Perština"),
    ("lv", "Lotyština"),
    ("bn", "Bengálština"),
    ("sr", "Srbština"),
    ("az", "Ázerbájdžánština"),
    ("sl", "Slovinština"),
    ("kn", "Kannadština"),
    ("et", "Estonština"),
    ("mk", "Makedonština"),
    ("br", "Bretonština"),
    ("eu", "Baskičtina"),
    ("is", "Islandština"),
    ("hy", "Arménština"),
    ("ne", "Nepálština"),
    ("mn", "Mongolština"),
    ("bs", "Bosenština"),
    ("kk", "Kazaština"),
    ("sq", "Albánština"),
    ("sw", "Svahilština"),
    ("gl", "Galicijština"),
    ("mr", "Maráthština"),
    ("pa", "Pandžábština"),
    ("si", "Sinhálština"),
    ("km", "Khmerština"),
    ("sn", "Šonština"),
    ("yo", "Jorubština"),
    ("so", "Somálština"),
    ("af", "Afrikánština"),
    ("oc", "Okcitánština"),
    ("ka", "Gruzínština"),
    ("be", "Běloruština"),
    ("tg", "Tádžičtina"),
    ("sd", "Sindhština"),
    ("gu", "Gudžarátština"),
    ("am", "Amharština"),
    ("yi", "Jidiš"),
    ("lo", "Laoština"),
    ("uz", "Uzbečtina"),
    ("fo", "Faerština"),
    ("ht", "Haitská kreolština"),
    ("ps", "Paštština"),
    ("tk", "Turkmenština"),
    ("nn", "Norština (nynorsk)"),
    ("mt", "Maltština"),
    ("sa", "Sanskrt"),
    ("lb", "Lucemburština"),
    ("my", "Barmština"),
    ("bo", "Tibetština"),
    ("tl", "Tagalština"),
    ("mg", "Malgaština"),
    ("as", "Ásámština"),
    ("tt", "Tatarština"),
    ("haw", "Havajština"),
    ("ln", "Lingalština"),
    ("ha", "Hauština"),
    ("ba", "Baškirština"),
    ("jw", "Javánština"),
    ("su", "Sundština"),
    ("yue", "Kantonština"),
];

/// Czech display name for a language code, falling back to the code itself.
pub fn label_for(code: &str) -> &str {
    LANGUAGES
        .iter()
        .find(|(c, _)| *c == code)
        .map(|(_, name)| *name)
        .unwrap_or(code)
}
